services:
  workspace:
    image: mcr.microsoft.com/devcontainers/typescript-node:4-24-trixie
    volumes:
      - source: ..
        target: /workspace
        type: bind
        consistency: cached
    command: sleep infinity
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - agent-manager-db:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

volumes:
  agent-manager-db:
